### PR TITLE
Bootstrap 5

### PR DESCRIPTION
**Pull request by ewohnlich**

### CODE REVIEW

**Comment by ewohnlich** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
Since this is only working in Plone 6 it would be great if you make a `2.3.x` branch from master and update `buildout.coredev` branch `5.2` with this branch. Then the checks for master only run for Plone 6. The failing test about `<section id="document-toc"` is strange though...

**Comment by gforcada** [comment]
I've seen that error on and off for a while on other PRs as well, it might come from `zpretty`ing some repositories, as the order might change? but then it should be consistent and not on and off 😵‍💫 🤔

**Comment by petschki** [comment]
> I've seen that error on and off for a while on other PRs as well, it might come from `zpretty`ing some repositories, as the order might change? but then it should be consistent and not on and off 😵‍💫 🤔

Thanks, good to know.

**Comment by petschki** [comment]
> > Since this is only working in Plone 6 it would be great if you make a `2.3.x` branch from master and update `buildout.coredev` branch `5.2` with this branch. Then the checks for master only run for Plone 6. The failing test about `<section id="document-toc"` is strange though...
> 
> I'm confused, why update the 5.2 branch there? Sorry, I'm not following the full pipeline setup here.

You see that there are Jenkins jobs here for Plone 5.2 which cannot work with this changes (iconresolver does not exist in 5.2) ... I'm fine with that since the Bootstrap classes also only work in Plone 6. The problem is, that `buildout.coredev/sources.cfg` has defined `plone.locking#master` as dependency and this should be fixed. But don't worry, I can take care of that today or tomorrow.

TODO:

- [ ] create branch `2.3.x` here
- [ ] update `buildout.coredev#5.2/sources.cfg` to use the `2.3.x` branch
- [ ] bump version of this PR to `3.0.0` since it is Plone 6 only

**Review by petschki — APPROVED** [review]

**Pull request merged**
